exclude: .*\.snap
ci:
  skip: [php-cs-fixer, php-cbf, php-lint]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/digitalpulp/pre-commit-php
    rev: 1.4.0
    hooks:
    - id: php-lint
    - id: php-cs-fixer
      files: \.(php)$
    - id: php-cbf
      files: \.(php)$
      args: [--standard=PSR1 -p]
