name: Build

on: push
permissions:
  checks: write
  issues: write

jobs:
  build_php:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
      - uses: "ramsey/composer-install@v1"
      - run: ./vendor/bin/phpunit tests/* --log-junit results.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: results.xml
